function cmp_backends()
car = char([36187 36710]); trk = char([36187 36947]);
M = { 'FM',       [car 'fm'],        'Racing_FM_NN_Metrics.mat'; ...
      'SafeFlow', [car 'safeflow'],  'Racing_SafeFlow_NN_Metrics.mat'; ...
      'PCFM',     [trk 'PCFM'],      'PCFM_Mech_Metrics.mat'; ...
      'FM-MPPI',  [trk 'FM-MPPI'],   'FM_MPPI_Mech_Metrics.mat'; ...
      'RoSD',     [trk 'RoSD'],      'RoSD_Mech_Metrics.mat'; ...
      'ReSD',     [trk 'ReSD'],      'ReSD_Mech_Metrics.mat'; ...
      'TVSD',     [trk 'TVSD'],      'TVSD_Mech_Metrics.mat' };
bak = fullfile('outputs','_backup_closedform_20260910');
fprintf('%-9s %-9s %8s %8s %8s %9s %9s\n','method','backend','Safety%','KL','CS','AS','Time');
for i = 1:size(M,1)
  for src = {fullfile('outputs',M{i,2}), fullfile(bak,M{i,2})}
    f = fullfile(src{1}, M{i,3});
    if ~isfile(f), fprintf('%-9s  (missing %s)\n', M{i,1}, f); continue; end
    S = load(f, 'metrics'); m = S.metrics;
    tag = 'quadprog'; if contains(src{1},'_backup_'), tag = 'closed'; end
    fprintf('%-9s %-9s %8.2f %8.4f %8.4f %9.4g %9.4f\n', M{i,1}, tag, ...
       100*m.safety, m.kl, m.cs, m.as, m.time_seconds);
  end
end
end
