function final_times()
car = char([36187 36710]); trk = char([36187 36947]);
M = { 'FM',       [car 'fm'],       'Racing_FM_NN'; ...
      'PCFM',     [trk 'PCFM'],     'PCFM_Mech'; ...
      'FM-MPPI',  [trk 'FM-MPPI'],  'FM_MPPI_Mech'; ...
      'RoSD',     [trk 'RoSD'],     'RoSD_Mech'; ...
      'ReSD',     [trk 'ReSD'],     'ReSD_Mech'; ...
      'TVSD',     [trk 'TVSD'],     'TVSD_Mech'; ...
      'SafeFlow', [car 'safeflow'], 'Racing_SafeFlow_NN'; ...
      'SafeFlow(paper)', [car 'safeflow_tbar05_paper'], 'Racing_SafeFlow_NN' };
fprintf('%-16s %-10s %8s %8s %8s %9s %10s\n','folder metric','backend','Safety%','KL','CS','AS','Time');
for i=1:size(M,1)
  d = fullfile('outputs', M{i,2});
  S = load(fullfile(d,[M{i,3} '_Metrics.mat']),'metrics'); m = S.metrics;
  R = load(fullfile(d,[M{i,3} '_Rollout.mat']),'rollout');
  bk = struct_field_default(R.rollout.options,'qp_backend','closed');
  fprintf('%-16s %-10s %8.2f %8.4f %8.4f %9.4g %10.4f\n', M{i,1}, bk, ...
     100*m.safety, m.kl, m.cs, m.as, m.time_seconds);
end
end
