% 初始化诊断 struct 的所有字段
function hocbf_diag = init_hocbf_diagnostics()
hocbf_diag.max_correction_norm = 0.0;
hocbf_diag.max_grad_norm = 0.0;
hocbf_diag.max_sigma2 = 0.0;
hocbf_diag.min_barrier_b = inf;
hocbf_diag.min_relaxed_barrier_b = inf;
hocbf_diag.min_psi1 = inf;
hocbf_diag.min_psi2 = inf;
hocbf_diag.min_terminal_h = inf;
hocbf_diag.max_hocbf_constraint_residual = -inf;
hocbf_diag.max_hocbf_relaxed_constraint_residual = -inf;
hocbf_diag.max_terminal_constraint_residual = -inf;
hocbf_diag.max_terminal_relaxed_constraint_residual = -inf;
hocbf_diag.min_qp_exitflag = inf;
hocbf_diag.max_qp_iterations = 0;
hocbf_diag.total_qp_solve_seconds = 0.0;
hocbf_diag.max_qp_active_constraint_count = 0;
hocbf_diag.trace_sample_idx = [];
hocbf_diag.trace_step_idx = [];
hocbf_diag.trace_stage_idx = [];
hocbf_diag.trace_t = [];
hocbf_diag.trace_hocbf_enabled = [];
hocbf_diag.trace_psi0 = [];
hocbf_diag.trace_psi1 = [];
hocbf_diag.trace_psi2 = [];
hocbf_diag.trace_psi1_dot = [];
hocbf_diag.trace_psi0_dot = [];
hocbf_diag.trace_b_dot = [];
hocbf_diag.trace_h_bar_dot = [];
hocbf_diag.trace_alpha1_psi0 = [];
hocbf_diag.trace_rho = [];
hocbf_diag.trace_rho_components = [];
hocbf_diag.trace_integral_bound = [];
hocbf_diag.trace_hocbf_constraint_residual = [];
hocbf_diag.trace_hocbf_relaxed_constraint_residual = [];
hocbf_diag.trace_hocbf_slack = [];
hocbf_diag.trace_u = [];
hocbf_diag.trace_correction_norm = [];
hocbf_diag.trace_max_abs_u = [];
hocbf_diag.trace_barrier_b = [];
hocbf_diag.trace_relaxed_barrier_b = [];
hocbf_diag.trace_h_bar = [];
hocbf_diag.trace_sigma2 = [];
hocbf_diag.trace_cumulative_variance = [];
hocbf_diag.trace_time_average_variance = [];
hocbf_diag.trace_terminal_ptzf_initial_bound = [];
hocbf_diag.trace_ptcbf_enabled = [];
hocbf_diag.trace_terminal_ptzf_bound = [];
hocbf_diag.trace_terminal_ptzf_bound_dot = [];
hocbf_diag.trace_terminal_inequality_h = [];
hocbf_diag.trace_terminal_beta_cap = [];
hocbf_diag.trace_terminal_beta_cap_dot = [];
hocbf_diag.trace_terminal_h = [];
hocbf_diag.trace_terminal_bound = [];
hocbf_diag.trace_terminal_constraint_residual = [];
hocbf_diag.trace_terminal_relaxed_constraint_residual = [];
hocbf_diag.trace_terminal_slack = [];
hocbf_diag.trace_anchor_clf_v = [];
hocbf_diag.trace_anchor_clf_bound = [];
hocbf_diag.trace_anchor_clf_residual = [];
hocbf_diag.trace_anchor_clf_raw_residual = [];
hocbf_diag.trace_anchor_clf_slack = [];
hocbf_diag.trace_qp_slack = [];
hocbf_diag.trace_anchor_clf_ptzf_bound = [];
hocbf_diag.trace_anchor_clf_ptzf_bound_dot = [];
hocbf_diag.trace_anchor_clf_ptzf_cg = [];
hocbf_diag.trace_anchor_clf_cpt = [];
hocbf_diag.trace_qp_exitflag = [];
hocbf_diag.trace_qp_iterations = [];
hocbf_diag.trace_qp_active_constraint_count = [];
% 障碍 CBF 诊断: 原始 h(不含 QP slack) 的逐步最小值、slack、约束行数、
% u=0 时的违反量。用于评价避障是否真的把点挡在障碍外(见 fix 4/5)。
hocbf_diag.trace_obstacle_h_min = [];
hocbf_diag.trace_obstacle_slack = [];
hocbf_diag.trace_obstacle_n_rows = [];
hocbf_diag.trace_obstacle_max_residual_without_u = [];
hocbf_diag.min_obstacle_h = inf;
hocbf_diag.min_obstacle_h_t = nan;
hocbf_diag.min_obstacle_h_sample_idx = nan;
hocbf_diag.min_obstacle_h_step_idx = nan;
hocbf_diag.max_obstacle_slack = 0.0;
hocbf_diag.obstacle_first_unsafe_t = nan;
hocbf_diag.obstacle_active_count = 0;   % 有点在障碍附近/内部(需修正)的步数
hocbf_diag.obstacle_eval_count = 0;     % 开启障碍 CBF 的子步总数
% 归一化前的行范数追踪(用于 slack 权重重新标定, w_new = w_old*r^2)。
hocbf_diag.trace_grad_norm = [];             % HOCBF/terminal 共用的 grad_x 行范数
hocbf_diag.trace_anchor_clf_grad_norm = [];  % anchor_clf 行范数
end
