function level_constraint = make_level_variance_constraint(cfg, level_prefix)
level_constraint = struct();

level_constraint.integral_uncertainty_budget = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_integral_uncertainty_budget']);
level_constraint.hocbf_enabled = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_hocbf_enabled']);
level_constraint.hocbf_alpha2 = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_hocbf_alpha2']);
level_constraint.hocbf_relaxation_bound = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_hocbf_relaxation_bound']);
level_constraint.psi1_margin = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_psi1_margin']);
level_constraint.diagnostics = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_diagnostics']);
level_constraint.ptcbf_enabled = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_ptcbf_enabled']);
level_constraint.terminal_variance_beta_final = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_terminal_variance_beta_final']);
level_constraint.terminal_variance_ptzf_initial_margin = struct_field_required( ...
    cfg.variance_constraint, ...
    [level_prefix, '_terminal_variance_ptzf_initial_margin']);
level_constraint.terminal_variance_ptzf_gamma = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_terminal_variance_ptzf_gamma']);
level_constraint.terminal_variance_alpha = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_terminal_variance_alpha']);
level_constraint.ptclf_enabled = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_ptclf_enabled']);
level_constraint.anchor_clf_ptzf_enabled = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_clf_ptzf_enabled'], true);
level_constraint.anchor_clf_ptzf_cg = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_clf_ptzf_cg'], 0.1);
level_constraint.anchor_clf_cpt = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_clf_cpt'], 1.0);
level_constraint.anchor_clf_ptzf_initial_margin = struct_field_default( ...
    cfg.variance_constraint, ...
    [level_prefix, '_anchor_clf_ptzf_initial_margin'], 1e-6);
level_constraint.slack_enabled = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_slack_enabled'], true);
level_constraint.hocbf_slack_enabled = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_hocbf_slack_enabled'], ...
    level_constraint.slack_enabled);
level_constraint.terminal_variance_slack_enabled = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_terminal_variance_slack_enabled'], ...
    level_constraint.slack_enabled);
% 只在 t >= 这个时刻之后才额外打开 terminal(PTCBF) 的 slack("生成后期"),
% 不设置时默认 inf，即不额外开启，行为和之前完全一致。HOCBF(integral)
% 全程保持硬约束，不做这个"后期放松"。
level_constraint.terminal_variance_slack_late_start_time = struct_field_default( ...
    cfg.variance_constraint, ...
    [level_prefix, '_terminal_variance_slack_late_start_time'], inf);
% 生成后期(t >= 这个时刻)让 CLF 变回硬约束，把 slack 挪给 PTCBF，
% 逼着 CLF 精确收敛到目标点。不设置时默认 inf，行为不变。
level_constraint.anchor_clf_slack_hard_after_time = struct_field_default( ...
    cfg.variance_constraint, ...
    [level_prefix, '_anchor_clf_slack_hard_after_time'], inf);
level_constraint.anchor_clf_slack_enabled = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_clf_slack_enabled'], ...
    level_constraint.slack_enabled);
level_constraint.anchor_clf_slack_weight = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_clf_slack_weight'], 1e4);
level_constraint.hocbf_slack_weight = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_hocbf_slack_weight'], ...
    level_constraint.anchor_clf_slack_weight);
level_constraint.terminal_variance_slack_weight = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_terminal_variance_slack_weight'], ...
    level_constraint.anchor_clf_slack_weight);
level_constraint.grad_tol = cfg.variance_constraint.grad_tol;
end
