function level_constraint = make_level_variance_constraint(cfg, level_prefix)
level_constraint = struct();

level_constraint.integral_uncertainty_budget = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_integral_uncertainty_budget']);
level_constraint.hocbf_enabled = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_hocbf_enabled']);
level_constraint.hocbf_alpha2 = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_hocbf_alpha2']);
level_constraint.hocbf_relaxation_bound = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_hocbf_relaxation_bound']);
level_constraint.psi1_margin = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_psi1_margin']);
level_constraint.diagnostics = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_diagnostics']);
level_constraint.ptcbf_enabled = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_ptcbf_enabled']);
level_constraint.terminal_variance_ptcbf_end_time = struct_field_default( ...
	cfg.variance_constraint, ...
	[level_prefix, '_terminal_variance_ptcbf_end_time'], inf);
level_constraint.terminal_variance_beta_final = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_terminal_variance_beta_final']);
level_constraint.terminal_variance_ptzf_initial_margin = struct_field_required( ...
    cfg.variance_constraint, ...
    [level_prefix, '_terminal_variance_ptzf_initial_margin']);
level_constraint.terminal_variance_ptzf_gamma = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_terminal_variance_ptzf_gamma']);
level_constraint.terminal_variance_alpha = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_terminal_variance_alpha']);
level_constraint.ptclf_enabled = struct_field_required( ...
    cfg.variance_constraint, [level_prefix, '_ptclf_enabled']);
level_constraint.closed_form_solver_enabled = struct_field_default( ...
    cfg.variance_constraint, ...
    [level_prefix, '_closed_form_solver_enabled'], false);
level_constraint.sequential_increment_qp_enabled = struct_field_default( ...
	cfg.variance_constraint, ...
	[level_prefix, '_sequential_increment_qp_enabled'], false);
ptclf_reference_field = ...
	[level_prefix, '_sequential_ptclf_reference_enabled'];
if isfield(cfg.variance_constraint, ptclf_reference_field)
	level_constraint.sequential_ptclf_reference_enabled = ...
		cfg.variance_constraint.(ptclf_reference_field);
end
% PTCLF 参考解里首块(S0)在 QP 目标中的权重。1.0 = 不加权(原行为)。
% 取 40 可抵消 S0 相对各增量块 40 倍的物理换算优势，避免 QP 把 P5 的修正
% 几乎全压在 S0 上(表现为整段平移而非调整段内形状)。
level_constraint.first_block_control_weight = struct_field_default( ...
	cfg.variance_constraint, ...
	[level_prefix, '_first_block_control_weight'], 1.0);
ptclf_reference_version_field = ...
	[level_prefix, '_sequential_ptclf_reference_impl_version'];
if isfield(cfg.variance_constraint, ptclf_reference_version_field)
	level_constraint.sequential_ptclf_reference_impl_version = ...
		cfg.variance_constraint.(ptclf_reference_version_field);
end
level_constraint.hocbf_filter_end_time = struct_field_default( ...
	cfg.variance_constraint, ...
	[level_prefix, '_hocbf_filter_end_time'], inf);
level_constraint.anchor_clf_ptzf_enabled = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_clf_ptzf_enabled'], true);
level_constraint.anchor_clf_ptzf_cg = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_clf_ptzf_cg'], 0.1);
level_constraint.anchor_clf_cpt = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_clf_cpt'], 1.0);
% 可选: [首点 cpt; 末点 cpt]，只在 sequential increment QP 的分端点
% PTCLF 里生效。不写时两端共用上面的 anchor_clf_cpt。
level_constraint.anchor_clf_endpoint_cpt = struct_field_default( ...
    cfg.variance_constraint, ...
    [level_prefix, '_anchor_clf_endpoint_cpt'], []);
level_constraint.anchor_clf_endpoint_ptzf_cg = struct_field_default( ...
    cfg.variance_constraint, ...
    [level_prefix, '_anchor_clf_endpoint_ptzf_cg'], []);
level_constraint.anchor_clf_endpoint_ptzf_initial_margin_ratios = ...
    struct_field_default(cfg.variance_constraint, ...
    [level_prefix, '_anchor_clf_endpoint_ptzf_initial_margin_ratios'], []);
level_constraint.anchor_clf_endpoint_ptzf_initial_margins = ...
    struct_field_default(cfg.variance_constraint, ...
    [level_prefix, '_anchor_clf_endpoint_ptzf_initial_margins'], []);
level_constraint.anchor_clf_ptzf_initial_margin = struct_field_default( ...
    cfg.variance_constraint, ...
    [level_prefix, '_anchor_clf_ptzf_initial_margin'], 1e-6);
level_constraint.slack_enabled = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_slack_enabled'], true);
level_constraint.hocbf_slack_enabled = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_hocbf_slack_enabled'], ...
    level_constraint.slack_enabled);
level_constraint.terminal_variance_slack_enabled = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_terminal_variance_slack_enabled'], ...
    level_constraint.slack_enabled);
% 统一的 slack 切换时刻: t < switch 时 PTCLF 带 slack、HOCBF/PTCBF 硬；
% t >= switch 后互换(PTCLF 变硬，HOCBF/PTCBF 开 slack)。默认 inf 即不切换。
slack_switch_time = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_slack_switch_time'], inf);
level_constraint.terminal_variance_slack_late_start_time = slack_switch_time;
level_constraint.hocbf_slack_late_start_time = slack_switch_time;
% PTCLF 和 obstacle 可以在不同时间变硬。未单独配置时继续使用
% 统一切换时刻，保持原来的行为。
level_constraint.anchor_clf_slack_hard_after_time = struct_field_default( ...
    cfg.variance_constraint, ...
    [level_prefix, '_anchor_clf_slack_hard_after_time'], ...
    slack_switch_time);
level_constraint.anchor_clf_slack_enabled = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_clf_slack_enabled'], ...
    level_constraint.slack_enabled);
level_constraint.anchor_clf_slack_weight = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_clf_slack_weight'], 1e4);
level_constraint.anchor_clf_first_slack_weight = struct_field_default( ...
    cfg.variance_constraint, ...
    [level_prefix, '_anchor_clf_first_slack_weight'], ...
    level_constraint.anchor_clf_slack_weight);
level_constraint.anchor_clf_last_slack_weight = struct_field_default( ...
    cfg.variance_constraint, ...
    [level_prefix, '_anchor_clf_last_slack_weight'], ...
    level_constraint.anchor_clf_slack_weight);
level_constraint.hocbf_slack_weight = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_hocbf_slack_weight'], ...
    level_constraint.anchor_clf_slack_weight);
level_constraint.terminal_variance_slack_weight = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_terminal_variance_slack_weight'], ...
    level_constraint.anchor_clf_slack_weight);
% 端点 snap-and-hold: 倒数这么多步时把首尾点钉成上层生成点并保持固定，
% 之后纯 flow matching 抹平段边界折角。0 表示关闭（保持旧行为）。
level_constraint.anchor_snap_flow_steps = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_snap_flow_steps'], 0);
snap_version_field = [level_prefix, '_anchor_snap_hold_impl_version'];
if isfield(cfg.variance_constraint, snap_version_field)
    % Cache key only: bump when snap-and-hold integration semantics change.
    level_constraint.anchor_snap_hold_impl_version = ...
        cfg.variance_constraint.(snap_version_field);
end
% 对照实验开关: true 时 snap 只覆盖位置(x,y)，不覆盖斜率(dx/ds,dy/ds)。
level_constraint.anchor_snap_position_only = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_snap_position_only'], false);
% 对照实验开关: true 时 PTCLF 全程只约束位置(x,y)，不约束斜率
% (dx/ds,dy/ds)。在 main_demo.m 里对 anchor_clf_indices/targets 生效。
level_constraint.anchor_clf_position_only = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_anchor_clf_position_only'], false);
% 按层覆盖梯度退化门槛，不写就三层共用 cfg.variance_constraint.grad_tol。
level_constraint.grad_tol = struct_field_default( ...
    cfg.variance_constraint, [level_prefix, '_grad_tol'], ...
    cfg.variance_constraint.grad_tol);

% 障碍 CBF（避障）。总开关 cfg.obstacle.enabled 与该层开关同时为真才生效。
% 几何/blow-up/slack 参数从 cfg.obstacle 读取；点->物理位置映射
% (obstacle_point_maps) 需要 data_transform，在 main_demo 里另行挂上。
obstacle_master = false;
if isfield(cfg, 'obstacle')
	obstacle_master = struct_field_default(cfg.obstacle, 'enabled', false);
end
level_constraint.obstacle_enabled = obstacle_master && struct_field_default( ...
	cfg.variance_constraint, [level_prefix, '_obstacle_enabled'], false);
level_constraint.obstacle_points = struct_field_default( ...
	cfg.variance_constraint, [level_prefix, '_obstacle_points'], []);
if level_constraint.obstacle_enabled
	level_constraint.obstacle_centers = cfg.obstacle.centers;
	level_constraint.obstacle_semi_axes = cfg.obstacle.semi_axes;
	% phi0/phi1_omega/slack_weight 默认继承 cfg.obstacle（三层共用），
	% 但允许按层用 [level_prefix, '_obstacle_phi0'] 等字段单独覆盖，
	% 不写就跟以前一样三层共用同一个值。
	level_constraint.obstacle_phi0 = struct_field_default( ...
		cfg.variance_constraint, [level_prefix, '_obstacle_phi0'], ...
		struct_field_default(cfg.obstacle, 'phi0', 2.0));
	level_constraint.obstacle_phi1_omega = struct_field_default( ...
		cfg.variance_constraint, [level_prefix, '_obstacle_phi1_omega'], ...
		struct_field_default(cfg.obstacle, 'phi1_omega', 4.0));
	% h<0 时允许前段采用小常增益，之后恢复原 blow-up 公式。
	% switch_time=0 时从起点就使用 blow-up，保持未配置层的旧行为。
	level_constraint.obstacle_phi1_early_gain = struct_field_default( ...
		cfg.variance_constraint, [level_prefix, '_obstacle_phi1_early_gain'], ...
		level_constraint.obstacle_phi1_omega);
	level_constraint.obstacle_phi1_switch_time = struct_field_default( ...
		cfg.variance_constraint, [level_prefix, '_obstacle_phi1_switch_time'], ...
		0.0);
	level_constraint.obstacle_activation_time = struct_field_default( ...
		cfg.variance_constraint, [level_prefix, '_obstacle_activation_time'], 0.0);
	level_constraint.obstacle_slack_enabled = struct_field_default( ...
		cfg.variance_constraint, [level_prefix, '_obstacle_slack_enabled'], ...
		struct_field_default(cfg.obstacle, 'slack_enabled', true));
	level_constraint.obstacle_slack_weight = struct_field_default( ...
		cfg.variance_constraint, [level_prefix, '_obstacle_slack_weight'], ...
		struct_field_default(cfg.obstacle, 'slack_weight', 1e4));
	% 前软后硬切换：复用该层统一的 slack_switch_time（和 hocbf/terminal
	% 相反方向，和 anchor_clf 同方向）。未设置时为 inf，即始终按
	% obstacle_slack_enabled（近似硬）。
	level_constraint.obstacle_slack_hard_after_time = struct_field_default( ...
		cfg.variance_constraint, ...
		[level_prefix, '_obstacle_slack_hard_after_time'], ...
		slack_switch_time);
	% 作用点落在椭圆中心驻点、真实梯度退化时的逃逸速度。留空(默认)则
	% 由 obstacle_cbf_info 按该障碍的短半轴自适应。
	level_constraint.obstacle_escape_speed = struct_field_default( ...
		cfg.variance_constraint, [level_prefix, '_obstacle_escape_speed'], ...
		struct_field_default(cfg.obstacle, 'escape_speed', []));
end
end
