function gp = optimize_endpoint_length_scale_hyperparameters( ...
    s_slices, x_slices, y_slices, gp, endpoint_window_width, ...
    project_dir, hyperparameter_relative_path, random_seed)
% Fit independent complete ARD length-scale vectors from short windows near
% t=0 and t=1. Every predictor must vary in each window; no length-scale
% component falls back to a full-domain value. The caller retains the one
% shared full-domain signal scale per output.

t0 = s_slices(1);
t1 = s_slices(end);
validateattributes(endpoint_window_width, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive', '<=', 0.5}, mfilename, ...
    'endpoint_window_width');
time_tolerance = 100 .* eps(max(1, max(abs(s_slices))));
start_mask = s_slices <= t0 + endpoint_window_width + time_tolerance;
end_mask = s_slices >= t1 - endpoint_window_width - time_tolerance;
if nnz(start_mask) < 2 || nnz(end_mask) < 2
    error(['Endpoint ARD windows must each contain at least two time ', ...
        'slices. Increase the endpoint window width or n_time_slices.']);
end

[hyper_dir, hyper_name, hyper_ext] = fileparts( ...
    fullfile(project_dir, hyperparameter_relative_path));
path0 = fullfile(hyper_dir, ...
    [hyper_name, '_EndpointARDStartWindowV3', hyper_ext]);
path1 = fullfile(hyper_dir, ...
    [hyper_name, '_EndpointARDEndWindowV3', hyper_ext]);

fprintf(['Optimizing or loading third-level start-window ARD ell_0 ', ...
    'from t in [%.6g, %.6g] (%d slices)...\n'], t0, ...
    max(s_slices(start_mask)), nnz(start_mask));
ell0 = fit_or_load_window_ard_length_scale( ...
    s_slices(start_mask), x_slices(start_mask, :, :), ...
    y_slices(start_mask, :, :), gp.n_pretrain, ...
    path0, random_seed);
fprintf(['Optimizing or loading third-level end-window ARD ell_1 ', ...
    'from t in [%.6g, %.6g] (%d slices)...\n'], ...
    min(s_slices(end_mask)), t1, nnz(end_mask));
ell1 = fit_or_load_window_ard_length_scale( ...
    s_slices(end_mask), x_slices(end_mask, :, :), ...
    y_slices(end_mask, :, :), gp.n_pretrain, ...
    path1, random_seed + 1);

% Clamp both tails with fixed absolute limits, independent of the
% full-domain ARD fit.  The upper limit removes components the window fit
% leaves at 1e5..1e21, for which the Gibbs amplitude factor
% prod_d sqrt(2 li lj/(li^2+lj^2)) over 21 input dimensions collapses
% to ~0.  The lower limit keeps the kernel wide enough to extrapolate:
% fitrgp is free to drive components toward 0 on the endpoint window, and
% components below ~1 leave the GP at its prior a short distance off the
% training manifold, where the variance gradient vanishes and the QP
% variance row loses first-order authority.  Both limits are applied
% before the endpoint-wide start/end scale factors.
length_scale_cap = struct_field_default(gp, ...
    'endpoint_length_scale_cap', 10.0);
validateattributes(length_scale_cap, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, mfilename, ...
    'length_scale_cap');
length_scale_floor = struct_field_default(gp, ...
    'endpoint_length_scale_floor', 2.0);
validateattributes(length_scale_floor, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive', '<', length_scale_cap}, ...
    mfilename, 'length_scale_floor');
n_clipped0 = nnz(ell0 > length_scale_cap);
n_clipped1 = nnz(ell1 > length_scale_cap);
n_floored0 = nnz(ell0 < length_scale_floor);
n_floored1 = nnz(ell1 < length_scale_floor);
ell0 = min(max(ell0, length_scale_floor), length_scale_cap);
ell1 = min(max(ell1, length_scale_floor), length_scale_cap);
fprintf(['Endpoint ARD absolute bounds [%.4g, %.4g] applied before ', ...
    'scaling: ell_0 clipped %d/%d and floored %d/%d, ', ...
    'ell_1 clipped %d/%d and floored %d/%d.\n'], ...
    length_scale_floor, length_scale_cap, ...
    n_clipped0, numel(ell0), n_floored0, numel(ell0), ...
    n_clipped1, numel(ell1), n_floored1, numel(ell1));
% Enlarge the start-of-rollout length scale after clamping.  At t=0 the
% state is a fresh 20-D source sample, so the nearest training point is
% far away (expected squared separation 2*20=40) and the GP sits at its
% prior.  A longer ell_0 lets distant training points contribute, which
% lowers the initial posterior variance.  The clamp above stays in charge
% of removing extreme components; this factor is applied on top of it.
start_scale = struct_field_default(gp, ...
    'start_length_scale_scale', 1.0);
validateattributes(start_scale, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, mfilename, 'start_scale');
if start_scale ~= 1.0
    ell0 = start_scale .* ell0;
    fprintf(['Start-window ARD scaled by %.4g after clamping ', ...
        '(median ell_0 %.4g -> %.4g).\n'], start_scale, ...
        median(ell0(2:end, :), 'all') ./ start_scale, ...
        median(ell0(2:end, :), 'all'));
end
% Shrink the end-of-rollout length scale.  Near t=1 the states have
% collapsed onto the data manifold, so a shorter ell_1 resolves finer
% structure there.  Applied after clamping, mirroring the start factor.
end_scale = struct_field_default(gp, 'end_length_scale_scale', 1.0);
validateattributes(end_scale, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, mfilename, 'end_scale');
if end_scale ~= 1.0
    ell1 = end_scale .* ell1;
    fprintf(['End-window ARD scaled by %.4g after clamping ', ...
        '(median ell_1 %.4g -> %.4g).\n'], end_scale, ...
        median(ell1(2:end, :), 'all') ./ end_scale, ...
        median(ell1(2:end, :), 'all'));
end
ratio = ell1 ./ ell0;
fprintf('ell_0: median=%.4g min=%.4g max=%.4g\n', ...
    median(ell0, 'all'), min(ell0, [], 'all'), max(ell0, [], 'all'));
fprintf('ell_1: median=%.4g min=%.4g max=%.4g\n', ...
    median(ell1, 'all'), min(ell1, [], 'all'), max(ell1, [], 'all'));
fprintf(['Final endpoint ratios ell_1/ell_0: %d increased, ', ...
    '%d decreased, %d unchanged; min=%.4g median=%.4g max=%.4g.\n'], ...
    sum(ratio > 1, 'all'), sum(ratio < 1, 'all'), ...
    sum(ratio == 1, 'all'), min(ratio, [], 'all'), ...
    median(ratio, 'all'), max(ratio, [], 'all'));

gp.length_scale_time_endpoint_enabled = true;
gp.length_scale_time_start_mat = ell0;
gp.length_scale_time_end_mat = ell1;
% SigmaL is needed during construction before the endpoint schedule is
% installed. Kernel evaluation itself uses the interpolated vectors.
gp.length_scale_mat = 0.5 .* (ell0 + ell1);

fprintf(['Third-level window-fitted ARD schedule: ', ...
    'ell_d(t)=ell_d,1+(ell_d,0-ell_d,1)(1-t)^%.6g, ', ...
    't0=%.6g, t1=%.6g.\n'], ...
    struct_field_default(gp, 'length_scale_time_endpoint_power', 1.0), ...
    t0, t1);
end

function ell = fit_or_load_window_ard_length_scale( ...
    s_window, x_window, y_window, n_pretrain_requested, ...
    cache_path, seed)
% Fit every ARD predictor from this endpoint window. A constant predictor
% is a configuration error because silently importing its full-domain
% length scale would violate the endpoint-only estimation assumption.

x_state = reshape(x_window, [], size(x_window, 3));
y = reshape(y_window, [], size(y_window, 3));
time_column = repmat(s_window(:), size(x_window, 2), 1);
x = [time_column, x_state];
[n_samples, input_dim] = size(x);
n_outputs = size(y, 2);

predictor_span = max(x, [], 1) - min(x, [], 1);
span_tolerance = 100 .* eps(max(1, max(abs(x), [], 1)));
variable_predictor_mask = predictor_span > span_tolerance;
if ~all(variable_predictor_mask)
    constant_predictors = find(~variable_predictor_mask);
    error(['Endpoint window cannot fit complete ARD because predictors ', ...
        '%s are constant. Increase the endpoint-window time/data ', ...
        'coverage; full-domain fallback is disabled.'], ...
        mat2str(constant_predictors));
end

endpoint_ard_cache_version = 4;

if isfile(cache_path)
    cached = load(cache_path);
    cache_proves_complete_endpoint_fit = ...
        (isfield(cached, 'EndpointARDCacheVersion') && ...
        cached.EndpointARDCacheVersion == endpoint_ard_cache_version) || ...
        (isfield(cached, 'VariablePredictorMask') && ...
        all(cached.VariablePredictorMask) && ...
        (~isfield(cached, 'FixedLengthScale') || ...
        isempty(cached.FixedLengthScale)));
    cache_valid = isfield(cached, 'EndpointLengthScale') && ...
        isequal(size(cached.EndpointLengthScale), [input_dim, n_outputs]) && ...
        all(isfinite(cached.EndpointLengthScale), 'all') && ...
        all(cached.EndpointLengthScale > 0, 'all') && ...
        cache_proves_complete_endpoint_fit && ...
        isfield(cached, 'WindowTimes') && ...
        isequaln(cached.WindowTimes, s_window(:)) && ...
        isfield(cached, 'VariablePredictorMask') && ...
        isequaln(cached.VariablePredictorMask, variable_predictor_mask);
    if cache_valid
        ell = cached.EndpointLengthScale;
        fprintf('Loading saved endpoint-window ARD length scales: %s\n', ...
            cache_path);
        return;
    end
end

n_pretrain = min(n_pretrain_requested, n_samples);
rng(seed);
pretrain_idx = randperm(n_samples, n_pretrain);
x_fit = x(pretrain_idx, variable_predictor_mask);
n_fitted_predictors = size(x_fit, 2);
ell = nan(input_dim, n_outputs);
for output_idx = 1:n_outputs
    fprintf('Running endpoint-window ARD fitrgp for output %d (%d/%d)...\n', ...
        output_idx, output_idx, n_outputs);
    fit_timer = tic;
    gp_model = fitrgp(x_fit, y(pretrain_idx, output_idx), ...
        'KernelFunction', 'ardsquaredexponential', 'Standardize', false);
    kernel_parameters = gp_model.KernelInformation.KernelParameters;
    fitted_length_scales = kernel_parameters(1:n_fitted_predictors);
    if any(~isfinite(fitted_length_scales)) || ...
            any(fitted_length_scales <= 0)
        error('Invalid endpoint-window ARD length scale for output %d.', ...
            output_idx);
    end
    ell(:, output_idx) = fitted_length_scales(:);
    fprintf('Finished endpoint-window output %d in %.1f seconds.\n', ...
        output_idx, toc(fit_timer));
end

EndpointLengthScale = ell;
WindowTimes = s_window(:);
VariablePredictorMask = variable_predictor_mask;
EndpointARDCacheVersion = endpoint_ard_cache_version;
save(cache_path, 'EndpointLengthScale', 'WindowTimes', ...
    'VariablePredictorMask', 'EndpointARDCacheVersion');
fprintf(['Saved endpoint-window ARD length scales (%d fitted predictors, ', ...
    'no fallback, %d samples): %s\n'], ...
    n_fitted_predictors, n_samples, ...
    cache_path);
end
