function print_hocbf_diagnostics(hocbf_diag, rollout_elapsed_seconds)
if isempty(hocbf_diag.trace_t)
	return;
end
if nargin < 2
	rollout_elapsed_seconds = nan;
end
disp(['HOCBF max correction norm: ', ...
	num2str(hocbf_diag.max_correction_norm)]);
disp(['HOCBF max uncertainty grad norm: ', ...
	num2str(hocbf_diag.max_grad_norm)]);
disp(['HOCBF max sigma^2: ', ...
	num2str(hocbf_diag.max_sigma2)]);
disp(['HOCBF nominal min barrier b: ', ...
	num2str(hocbf_diag.min_barrier_b)]);
if isfield(hocbf_diag, 'trace_hocbf_enabled') && ...
		~any(logical(hocbf_diag.trace_hocbf_enabled))
	disp('HOCBF disabled.');
else
	disp(['PTCBF/HOCBF min relaxed barrier b: ', ...
		num2str(hocbf_diag.min_relaxed_barrier_b)]);
	disp(['PTCBF/HOCBF min psi1: ', ...
		num2str(hocbf_diag.min_psi1)]);
	if isfinite(hocbf_diag.min_psi1)
		disp(['  min psi1 context: sample ', ...
			num2str(hocbf_diag.min_psi1_sample_idx), ', step ', ...
			num2str(hocbf_diag.min_psi1_step_idx), ', stage ', ...
			hocbf_diag.min_psi1_stage, ', t ', ...
			num2str(hocbf_diag.min_psi1_t)]);
		disp(['  min psi1 terms: sigma2 beta ', ...
			num2str(hocbf_diag.min_psi1_sigma2), ', cumulative ', ...
			num2str(hocbf_diag.min_psi1_cumulative_variance), ...
			', time-average ', ...
			num2str(hocbf_diag.min_psi1_time_average_variance)]);
		disp(['  min psi1 barrier terms: b ', ...
			num2str(hocbf_diag.min_psi1_barrier_b), ', psi0=b+hbar ', ...
			num2str(hocbf_diag.min_psi1_psi0), ', hbar ', ...
			num2str(hocbf_diag.min_psi1_h_bar)]);
		disp(['  min psi1 derivative terms: psi0_dot ', ...
			num2str(hocbf_diag.min_psi1_psi0_dot), ', hbar_dot ', ...
			num2str(hocbf_diag.min_psi1_h_bar_dot), ...
			', alpha0*psi0 ', ...
			num2str(hocbf_diag.min_psi1_alpha_psi0)]);
	end
	disp(['PTCBF/HOCBF min psi2: ', ...
		num2str(hocbf_diag.min_psi2)]);
	disp(['HOCBF max constraint residual: ', ...
		num2str(hocbf_diag.max_hocbf_constraint_residual)]);
	if isfield(hocbf_diag, 'max_hocbf_relaxed_constraint_residual')
		disp(['HOCBF max relaxed residual after QP slack: ', ...
			num2str(hocbf_diag.max_hocbf_relaxed_constraint_residual)]);
	end
	if isfield(hocbf_diag, 'trace_hocbf_slack') && ...
			~isempty(hocbf_diag.trace_hocbf_slack) && ...
			any(isfinite(hocbf_diag.trace_hocbf_slack))
		disp(['HOCBF max slack: ', ...
			num2str(max(hocbf_diag.trace_hocbf_slack))]);
	end
end
if isfinite(hocbf_diag.min_terminal_h)
	disp(['Terminal PTCBF min relaxed barrier hbar-h_T: ', ...
		num2str(hocbf_diag.min_terminal_h)]);
	disp(['  min terminal barrier context: sample ', ...
		num2str(hocbf_diag.min_terminal_h_sample_idx), ', step ', ...
		num2str(hocbf_diag.min_terminal_h_step_idx), ', stage ', ...
		hocbf_diag.min_terminal_h_stage, ', t ', ...
		num2str(hocbf_diag.min_terminal_h_t)]);
	disp(['  min h_T terms: beta ', ...
		num2str(hocbf_diag.min_terminal_h_sigma2), ...
		', h=beta-beta_final ', ...
		num2str(hocbf_diag.min_terminal_h_inequality_h), ...
		', hbar ', ...
		num2str(hocbf_diag.min_terminal_h_ptzf_bound), ...
		', beta_cap ', ...
		num2str(hocbf_diag.min_terminal_h_beta_cap), ...
		', residual ', ...
		num2str(hocbf_diag.min_terminal_h_residual)]);
	disp(['Terminal PTCBF max constraint residual: ', ...
		num2str(hocbf_diag.max_terminal_constraint_residual)]);
	if isfield(hocbf_diag, 'max_terminal_relaxed_constraint_residual')
		disp(['Terminal PTCBF max relaxed residual after QP slack: ', ...
			num2str(hocbf_diag.max_terminal_relaxed_constraint_residual)]);
	end
	if isfield(hocbf_diag, 'trace_terminal_slack') && ...
			~isempty(hocbf_diag.trace_terminal_slack) && ...
			any(isfinite(hocbf_diag.trace_terminal_slack))
		disp(['Terminal PTCBF max slack: ', ...
			num2str(max(hocbf_diag.trace_terminal_slack))]);
	end
	if isfield(hocbf_diag, 'trace_anchor_clf_residual') && ...
			~isempty(hocbf_diag.trace_anchor_clf_residual) && ...
			any(isfinite(hocbf_diag.trace_anchor_clf_residual))
		disp(['Anchor CLF max constraint residual: ', ...
			num2str(max(hocbf_diag.trace_anchor_clf_residual))]);
	end
	if isfield(hocbf_diag, 'trace_anchor_clf_raw_residual') && ...
			~isempty(hocbf_diag.trace_anchor_clf_raw_residual) && ...
			any(isfinite(hocbf_diag.trace_anchor_clf_raw_residual))
		disp(['Anchor CLF max raw residual: ', ...
			num2str(max(hocbf_diag.trace_anchor_clf_raw_residual))]);
	end
	if isfield(hocbf_diag, 'trace_anchor_clf_slack') && ...
			~isempty(hocbf_diag.trace_anchor_clf_slack) && ...
			any(isfinite(hocbf_diag.trace_anchor_clf_slack))
		disp(['Anchor CLF max slack: ', ...
			num2str(max(hocbf_diag.trace_anchor_clf_slack))]);
	end
	if isfield(hocbf_diag, 'trace_qp_slack') && ...
			~isempty(hocbf_diag.trace_qp_slack) && ...
			any(isfinite(hocbf_diag.trace_qp_slack))
		disp(['QP max slack over all constraints: ', ...
			num2str(max(hocbf_diag.trace_qp_slack))]);
	end
	disp(['QP min exitflag: ', num2str(hocbf_diag.min_qp_exitflag), ...
		', max active constraints: ', ...
		num2str(hocbf_diag.max_qp_active_constraint_count)]);
	if isfield(hocbf_diag, 'max_qp_iterations')
		disp(['QP max iterations used (cap 200 unless changed): ', ...
			num2str(hocbf_diag.max_qp_iterations)]);
	end
	if isfield(hocbf_diag, 'total_qp_solve_seconds')
		if isfinite(rollout_elapsed_seconds) && rollout_elapsed_seconds > 0
			disp(['QP total solve time: ', ...
				num2str(hocbf_diag.total_qp_solve_seconds, '%.2f'), ...
				's / rollout total ', ...
				num2str(rollout_elapsed_seconds, '%.2f'), 's (', ...
				num2str(100 * hocbf_diag.total_qp_solve_seconds / ...
				rollout_elapsed_seconds, '%.1f'), '%)']);
		else
			disp(['QP total solve time: ', ...
				num2str(hocbf_diag.total_qp_solve_seconds, '%.2f'), 's']);
		end
	end
end
% 归一化前行范数统计(供 slack 权重重新标定用, w_new = w_old * median(r)^2)。
if isfield(hocbf_diag, 'trace_grad_norm') && ~isempty(hocbf_diag.trace_grad_norm)
	gn = hocbf_diag.trace_grad_norm;
	disp(['HOCBF/terminal grad_x row norm (pre-normalization) median/mean/max: ', ...
		num2str(median(gn), '%.4g'), ' / ', num2str(mean(gn), '%.4g'), ' / ', ...
		num2str(max(gn), '%.4g')]);
end
if isfield(hocbf_diag, 'trace_anchor_clf_grad_norm') && ...
		~isempty(hocbf_diag.trace_anchor_clf_grad_norm) && ...
		any(hocbf_diag.trace_anchor_clf_grad_norm > 0)
	cn = hocbf_diag.trace_anchor_clf_grad_norm(hocbf_diag.trace_anchor_clf_grad_norm > 0);
	disp(['Anchor CLF grad row norm (pre-normalization) median/mean/max: ', ...
		num2str(median(cn), '%.4g'), ' / ', num2str(mean(cn), '%.4g'), ' / ', ...
		num2str(max(cn), '%.4g')]);
end
% 障碍 CBF 诊断(fix 5): 独立打印, 无 OOD 控制时也要能看到。
% min_obstacle_h 是"原始 h"(不含 QP slack), 才是真实安全度量(fix 4)。
if isfield(hocbf_diag, 'obstacle_eval_count') && hocbf_diag.obstacle_eval_count > 0
	disp(['Obstacle CBF min RAW h over rollout (slack-independent): ', ...
		num2str(hocbf_diag.min_obstacle_h), ' at t=', ...
		num2str(hocbf_diag.min_obstacle_h_t), ' (sample ', ...
		num2str(hocbf_diag.min_obstacle_h_sample_idx), ', step ', ...
		num2str(hocbf_diag.min_obstacle_h_step_idx), ')']);
	disp(['Obstacle CBF max slack: ', ...
		num2str(hocbf_diag.max_obstacle_slack)]);
	disp(['Obstacle CBF activation ratio (sub-steps needing correction): ', ...
		num2str(100 * hocbf_diag.obstacle_active_count / ...
		hocbf_diag.obstacle_eval_count, '%.1f'), '% (', ...
		num2str(hocbf_diag.obstacle_active_count), '/', ...
		num2str(hocbf_diag.obstacle_eval_count), ')']);
	if isfinite(hocbf_diag.obstacle_first_unsafe_t)
		disp(['Obstacle CBF first RAW h<0 at t=', ...
			num2str(hocbf_diag.obstacle_first_unsafe_t), ...
			' (rollout 中途有点进障碍; 最终是否安全看 t=1 曲线评价)']);
	else
		disp('Obstacle CBF: RAW h >= 0 at all evaluated sub-steps.');
	end
end
end
