function print_hocbf_diagnostics(hocbf_diag)
if isempty(hocbf_diag.trace_t)
	return;
end
disp(['HOCBF max correction norm: ', ...
	num2str(hocbf_diag.max_correction_norm)]);
disp(['HOCBF max uncertainty grad norm: ', ...
	num2str(hocbf_diag.max_grad_norm)]);
disp(['HOCBF max sigma^2: ', ...
	num2str(hocbf_diag.max_sigma2)]);
disp(['HOCBF nominal min barrier b: ', ...
	num2str(hocbf_diag.min_barrier_b)]);
disp(['PTCBF/HOCBF min relaxed barrier b: ', ...
	num2str(hocbf_diag.min_relaxed_barrier_b)]);
disp(['PTCBF/HOCBF min psi1: ', ...
	num2str(hocbf_diag.min_psi1)]);
if isfinite(hocbf_diag.min_psi1)
	disp(['  min psi1 context: sample ', ...
		num2str(hocbf_diag.min_psi1_sample_idx), ', step ', ...
		num2str(hocbf_diag.min_psi1_step_idx), ', stage ', ...
		hocbf_diag.min_psi1_stage, ', t ', ...
		num2str(hocbf_diag.min_psi1_t)]);
	disp(['  min psi1 terms: sigma2 beta ', ...
		num2str(hocbf_diag.min_psi1_sigma2), ', cumulative ', ...
		num2str(hocbf_diag.min_psi1_cumulative_variance), ...
		', time-average ', ...
		num2str(hocbf_diag.min_psi1_time_average_variance)]);
	disp(['  min psi1 barrier terms: b ', ...
		num2str(hocbf_diag.min_psi1_barrier_b), ', psi0=b+hbar ', ...
		num2str(hocbf_diag.min_psi1_psi0), ', hbar ', ...
		num2str(hocbf_diag.min_psi1_h_bar)]);
	disp(['  min psi1 derivative terms: psi0_dot ', ...
		num2str(hocbf_diag.min_psi1_psi0_dot), ', hbar_dot ', ...
		num2str(hocbf_diag.min_psi1_h_bar_dot), ...
		', alpha0*psi0 ', ...
		num2str(hocbf_diag.min_psi1_alpha_psi0)]);
end
disp(['PTCBF/HOCBF min psi2: ', ...
	num2str(hocbf_diag.min_psi2)]);
disp(['HOCBF max constraint residual: ', ...
	num2str(hocbf_diag.max_hocbf_constraint_residual)]);
end
