function result = regenerate_hierarchy_parent(ctx, parent_idx, upstream_round)
%REGENERATE_HIERARCHY_PARENT Regenerate one L1 parent and all of its L2 segments.

first_filter = ctx.first_filter;
first_filter.target_trajectory_count = 1;
first_filter.parallel_trajectory_batch_size = 1;
first_attempt_block = struct_field_default(first_filter, ...
	'max_attempts_per_trajectory', 100);
first_initial_reserve = ctx.n_first_parents * first_attempt_block;
lineage_idx = (parent_idx - 1) * ctx.max_upstream_retries + ...
	upstream_round - 1;
first_filter.base_seed = double(ctx.first_filter.base_seed) + ...
	first_initial_reserve + ...
	(ctx.seed_namespace + lineage_idx) * first_attempt_block;
first_constraint = subset_rollout_constraint(ctx.first_constraint, ...
	parent_idx, 1);
first_constraint.live_trajectory_plot_enabled = false;
[result.first_times, result.first_path, result.first_diagnostics, ...
	result.first_x_init, result.first_seeds, result.first_acceptance, ...
	result.first_uncertainty] = generate_valid_second_level_rollouts( ...
	ctx.first_model, first_constraint, 1, 1, ctx.first_state_dim, ...
	ctx.first_point_count, ctx.first_transform, ctx.t_min, ctx.t_max, ...
	ctx.first_time_steps, [], ctx.parallel, first_filter);

final_standardized = reshape(result.first_path(end, 1, :), 1, []);
result.first_final_physical = final_standardized .* ...
	ctx.first_transform.std' + ctx.first_transform.mean';
first_points = reshape(result.first_final_physical, ...
	ctx.first_feature_dim, [])';
result.first_points = normalize_tangent_features(reshape(first_points, ...
	size(first_points, 1), 1, size(first_points, 2)));

updated_anchors = ctx.second_anchor_points;
updated_anchors(:, parent_idx, :) = result.first_points;
second_constraint = ctx.second_constraint;
if struct_field_default(second_constraint, 'ptclf_enabled', false)
	[targets, indices] = build_anchor_clf_targets(updated_anchors, ...
		ctx.n_first_parents, ctx.n_second_samples, ctx.n_second_segments, ...
		ctx.points_per_segment, ctx.second_transform);
	if struct_field_default(second_constraint, ...
			'anchor_clf_position_only', false)
		keep = mod(0:(numel(indices) - 1), 4) < 2;
		indices = indices(keep);
		targets = targets(:, keep);
	end
	second_constraint.anchor_clf_targets = targets;
	second_constraint.anchor_clf_indices = indices;
end
result.second_constraint = second_constraint;
result.second_anchor_points = updated_anchors;

second_filter = ctx.second_filter;
second_filter.target_trajectory_count = 1;
second_filter.parallel_trajectory_batch_size = 1;
second_filter.return_on_exhaustion = true;
second_attempt_block = second_filter.max_attempts_per_trajectory * ...
	ctx.n_second_segments;
second_initial_reserve = ctx.n_second_parents * second_attempt_block;
second_filter.base_seed = double(ctx.second_filter.base_seed) + ...
	second_initial_reserve + ...
	(ctx.seed_namespace + lineage_idx) * second_attempt_block;
local_constraint = subset_rollout_constraint(second_constraint, ...
	parent_idx, ctx.n_second_segments);
local_constraint.live_trajectory_plot_enabled = false;
[result.second_times, result.second_path, result.second_diagnostics, ...
	result.second_x_init, result.second_seeds, result.second_acceptance, ...
	result.second_uncertainty, result.second_exhaustion] = ...
	generate_valid_second_level_rollouts(ctx.second_model, local_constraint, ...
	1, ctx.n_second_segments, ctx.second_state_dim, ctx.points_per_segment, ...
	ctx.second_transform, ctx.t_min, ctx.t_max, ctx.second_time_steps, ...
	ctx.second_refine, ctx.parallel, second_filter);
end
