function combined = replace_seed_acceptance_segment_block(combined, ...
	parent_idx, segment_indices, local)
%REPLACE_SEED_ACCEPTANCE_SEGMENT_BLOCK Replace contiguous/arbitrary child segments.

segment_indices = segment_indices(:)';
segment_fields = { ...
	'accepted_seeds', 'segment_attempt_counts', ...
	'segment_search_max_excess', 'segment_final_max_excess', ...
	'segment_final_min_margin', 'segment_final_min_hocbf_psi0', ...
	'segment_final_min_hocbf_psi1', 'segment_final_min_track_point_h', ...
	'segment_final_min_obstacle_point_h', ...
	'segment_final_min_track_line_h', ...
	'segment_final_min_obstacle_line_h'};
for idx = 1:numel(segment_fields)
	name = segment_fields{idx};
	if isfield(combined, name) && isfield(local, name) && ...
			~isempty(local.(name))
		combined.(name)(parent_idx, segment_indices) = local.(name)(1, :);
	end
end

% Recompute every parent-level aggregate from its segment diagnostics.
combined = refresh_parent(combined, parent_idx);
end

function value = refresh_parent(value, parent_idx)
if isfield(value, 'segment_attempt_counts')
	value.attempt_counts(parent_idx, 1) = ...
		max(value.segment_attempt_counts(parent_idx, :));
end
max_pairs = { ...
	'search_max_excess', 'segment_search_max_excess'; ...
	'final_max_excess', 'segment_final_max_excess'};
for idx = 1:size(max_pairs, 1)
	if isfield(value, max_pairs{idx, 1}) && isfield(value, max_pairs{idx, 2})
		value.(max_pairs{idx, 1})(parent_idx, 1) = max( ...
			value.(max_pairs{idx, 2})(parent_idx, :));
	end
end
min_pairs = { ...
	'final_min_margin', 'segment_final_min_margin'; ...
	'final_min_hocbf_psi0', 'segment_final_min_hocbf_psi0'; ...
	'final_min_hocbf_psi1', 'segment_final_min_hocbf_psi1'; ...
	'final_min_track_point_h', 'segment_final_min_track_point_h'; ...
	'final_min_obstacle_point_h', 'segment_final_min_obstacle_point_h'; ...
	'final_min_track_line_h', 'segment_final_min_track_line_h'; ...
	'final_min_obstacle_line_h', 'segment_final_min_obstacle_line_h'};
for idx = 1:size(min_pairs, 1)
	if isfield(value, min_pairs{idx, 1}) && isfield(value, min_pairs{idx, 2})
		value.(min_pairs{idx, 1})(parent_idx, 1) = min( ...
			value.(min_pairs{idx, 2})(parent_idx, :));
	end
end
end
