function combined = replace_seed_acceptance_parent(combined, parent_idx, local)
%REPLACE_SEED_ACCEPTANCE_PARENT Replace one parent's acceptance diagnostics.

parent_fields = { ...
	'attempt_counts', 'search_max_excess', 'final_max_excess', ...
	'final_min_margin', 'final_min_hocbf_psi0', 'final_min_hocbf_psi1', ...
	'final_min_track_point_h', 'final_min_obstacle_point_h', ...
	'final_min_track_line_h', 'final_min_obstacle_line_h'};
for idx = 1:numel(parent_fields)
	name = parent_fields{idx};
	if isfield(combined, name) && isfield(local, name) && ...
			~isempty(combined.(name)) && ~isempty(local.(name))
		combined.(name)(parent_idx, :) = local.(name)(1, :);
	end
end

segment_fields = { ...
	'accepted_seeds', 'segment_attempt_counts', ...
	'segment_search_max_excess', 'segment_final_max_excess', ...
	'segment_final_min_margin', 'segment_final_min_hocbf_psi0', ...
	'segment_final_min_hocbf_psi1', 'segment_final_min_track_point_h', ...
	'segment_final_min_obstacle_point_h', ...
	'segment_final_min_track_line_h', ...
	'segment_final_min_obstacle_line_h'};
for idx = 1:numel(segment_fields)
	name = segment_fields{idx};
	if isfield(combined, name) && isfield(local, name) && ...
			~isempty(combined.(name)) && ~isempty(local.(name))
		combined.(name)(parent_idx, :) = local.(name)(1, :);
	end
end
end
