function combined = replace_seed_acceptance_segment(combined, parent_idx, segment_idx, local)
%REPLACE_SEED_ACCEPTANCE_SEGMENT Replace one segment and refresh parent summaries.

segment_fields = { ...
	'accepted_seeds', 'segment_attempt_counts', ...
	'segment_search_max_excess', 'segment_final_max_excess', ...
	'segment_final_min_margin', 'segment_final_min_hocbf_psi0', ...
	'segment_final_min_hocbf_psi1', 'segment_final_min_track_point_h', ...
	'segment_final_min_obstacle_point_h', ...
	'segment_final_min_track_line_h', ...
	'segment_final_min_obstacle_line_h'};
for idx = 1:numel(segment_fields)
	name = segment_fields{idx};
	if ~isfield(combined, name)
		continue;
	end
	if isfield(local, name) && ~isempty(local.(name))
		local_value = local.(name)(1);
	else
		parent_name = erase(name, 'segment_');
		if ~isfield(local, parent_name) || isempty(local.(parent_name))
			continue;
		end
		local_value = local.(parent_name)(1);
	end
	combined.(name)(parent_idx, segment_idx) = local_value;
end

if isfield(combined, 'segment_attempt_counts')
	combined.attempt_counts(parent_idx, 1) = ...
		max(combined.segment_attempt_counts(parent_idx, :));
end
max_pairs = { ...
	'search_max_excess', 'segment_search_max_excess'; ...
	'final_max_excess', 'segment_final_max_excess'};
for idx = 1:size(max_pairs, 1)
	if isfield(combined, max_pairs{idx, 1}) && ...
			isfield(combined, max_pairs{idx, 2})
		combined.(max_pairs{idx, 1})(parent_idx, 1) = max( ...
			combined.(max_pairs{idx, 2})(parent_idx, :));
	end
end
min_pairs = { ...
	'final_min_margin', 'segment_final_min_margin'; ...
	'final_min_hocbf_psi0', 'segment_final_min_hocbf_psi0'; ...
	'final_min_hocbf_psi1', 'segment_final_min_hocbf_psi1'; ...
	'final_min_track_point_h', 'segment_final_min_track_point_h'; ...
	'final_min_obstacle_point_h', 'segment_final_min_obstacle_point_h'; ...
	'final_min_track_line_h', 'segment_final_min_track_line_h'; ...
	'final_min_obstacle_line_h', 'segment_final_min_obstacle_line_h'};
for idx = 1:size(min_pairs, 1)
	if isfield(combined, min_pairs{idx, 1}) && ...
			isfield(combined, min_pairs{idx, 2})
		combined.(min_pairs{idx, 1})(parent_idx, 1) = min( ...
			combined.(min_pairs{idx, 2})(parent_idx, :));
	end
end
end
