function rerun_nn_quadprog_validate(n_gen)
%RERUN_NN_QUADPROG_VALIDATE  A/B the closed-form and quadprog QP backends.
% Small-n check that switching the solver leaves the trajectories unchanged
% (to solver tolerance) and only changes the run time.
if nargin < 1 || isempty(n_gen), n_gen = 2; end
car = char([36187 36710]); trk = char([36187 36947]);
src = fullfile('outputs', [car 'safeflow']);
N = load(fullfile(src, 'Racing_SafeFlow_NN_Net.mat')); net = N.net;
A = load(fullfile(src, 'Racing_SafeFlow_NN_Rollout.mat')); arch = A.rollout;
seeds = arch.trajectory_seeds(1:n_gen);

base = struct('trajectory_seeds', seeds, 'u_per_stage', false, ...
    'fmincon_fallback', false, 'record_path', false, 'activation_time', 0, ...
    'terminal_filter', false, 'phi1_form', 'constant', 'phi1_alpha', 1.0, ...
    'phi1_switch_time', 0);
cases = { ...
  'SafeFlow', @(o) safeflow_nn_rollout(net, 'safeflow', n_gen, o), ...
      merge(rmfield(base,{'phi1_form','phi1_alpha','phi1_switch_time'}), ...
            struct('terminal_filter', true, 'phi1_omega', 50)); ...
  'RoSD', @(o) safeflow_nn_rollout(net, 'safeflow', n_gen, o), ...
      merge(base, struct('slack_enabled', false)); ...
  'ReSD', @(o) safeflow_nn_rollout(net, 'safeflow', n_gen, o), ...
      merge(base, struct('resd_weight_schedule', [100 0 0.9])); ...
  'TVSD', @(o) safeflow_nn_rollout(net, 'safeflow', n_gen, o), ...
      merge(base, struct('gamma_mode','sigmoid','gamma_min',-1.0, ...
            'gamma_steepness',10,'gamma_midpoint',0.5,'phi1_alpha',10, ...
            'phi0',10,'slack_enabled',false)); ...
  'PCFM', @(o) pcfm_nn_rollout(net, n_gen, o), ...
      struct('trajectory_seeds', seeds, 'record_path', false) };

ws1 = warning('off','MATLAB:nearlySingularMatrix');
ws2 = warning('off','MATLAB:singularMatrix');
fprintf('%-10s %12s %12s %10s %14s\n','method','closed s','quadprog s','ratio','max|dpoints|');
for i = 1:size(cases,1)
    o = cases{i,3}; f = cases{i,2};
    o.qp_backend = 'closed';   t=tic; r1 = f(o); t1 = toc(t);
    o.qp_backend = 'quadprog'; t=tic; r2 = f(o); t2 = toc(t);
    d = max(abs(r1.points(:) - r2.points(:)));
    fprintf('%-10s %12.2f %12.2f %10.1fx %14.3e\n', cases{i,1}, t1, t2, t2/t1, d);
end
warning(ws1); warning(ws2);
end

function a = merge(a, b)
f = fieldnames(b);
for k = 1:numel(f), a.(f{k}) = b.(f{k}); end
end
