function report=test_strict_cem_sigmas()
root='C:\Users\JieJi\BA\matlab';
L=load(fullfile(root,'outputs','赛道UniConFlow_Stage1_ParamSweep', ...
    'Stage1_Best_100Seeds.mat'),'result');
q=7;a=L.result.out;scene=uniconflow_paper_project_scene();
one=struct('states',a.states(:,:,q),'actions',a.actions(:,:,q), ...
    'spec',a.spec,'trajectory',a.trajectory(:,q),'mode',a.mode);
sigmas={[0.01;0.2],[0.03;0.5],[0.05;1.0]};rows=cell(3,1);
pool=gcp('nocreate');if isempty(pool)||pool.NumWorkers~=3
    if ~isempty(pool),delete(pool);end;parpool('Processes',3);end
state_constraint=scene.state_constraint;
state_constraint_batch=scene.state_constraint_batch;
state_constraint_rows_batch=scene.state_constraint_rows_batch;
seedq=L.result.seeds(q);
parfor i=1:3
    sg=sigmas{i};base=double(mod(uint64(seedq),uint64(2^31-10000)));
    o=struct('cem_population',512,'cem_elite',32,'cem_iterations',20, ...
        'n_pad',10,'n_rec',20,'cem_sigma',sg,'lambda_obs',1e8, ...
        'lambda_track',1e8,'paper_strict',true, ...
        'max_seconds_per_trajectory',120,'seed',base+8200+i, ...
        'state_constraint',state_constraint, ...
        'state_constraint_batch',state_constraint_batch, ...
        'state_constraint_rows_batch',state_constraint_rows_batch);
    t=tic;r=uniconflow_paper_cem_refine(one,o);seconds=toc(t);
    rows{i}=struct('sigma_delta',sg(1),'sigma_tau',sg(2), ...
        'certified',all(r.certified),'violations',r.state_violations_after, ...
        'passes',r.cem_passes,'seconds',seconds);
end
report=struct2table(vertcat(rows{:}));disp(report);
save(fullfile(root,'outputs','赛道UniConFlow_Stage1_ParamSweep', ...
    'StrictCEM_q007_SigmaSweep.mat'),'report','-v7.3');
end
