function report=tune_uniconflow_stage1_params(n_test,workers)
%TUNE_UNICONFLOW_STAGE1_PARAMS Parameter-only Stage-1 PTZF sweep.
if nargin<1,n_test=20;end
if nargin<2,workers=6;end
root='C:\Users\JieJi\BA\matlab';
formal=fullfile(root,'outputs','赛道UniConFlow_Paper_FastCertified_100');
N=load(fullfile(formal,'inputs','UniConFlow_Paper_Reconstructed_Net.mat'),'net');
D=load(fullfile(formal,'inputs','UniConFlow_Paper_Reconstructed_Dataset.mat'),'data');
L=load(fullfile(formal,'Stage1_All_Trajectories.mat'),'stage_cache');
seeds=L.stage_cache.trajectory_seeds(1:n_test);scene=uniconflow_paper_project_scene();
scur=D.data.states(:,1,1);state_constraint=scene.state_constraint;
dt_data=D.data.dt;net=N.net;

cfg={ ...
    struct('name','baseline','P_delta',1e3,'c_PT',2,'c_g',1), ...
    struct('name','Pdelta_3e3','P_delta',3e3,'c_PT',2,'c_g',1), ...
    struct('name','Pdelta_1e4','P_delta',1e4,'c_PT',2,'c_g',1), ...
    struct('name','Pdelta_3e4','P_delta',3e4,'c_PT',2,'c_g',1), ...
    struct('name','Pdelta_1e5','P_delta',1e5,'c_PT',2,'c_g',1), ...
    struct('name','Pdelta1e4_cpt1p5','P_delta',1e4,'c_PT',1.5,'c_g',1), ...
    struct('name','Pdelta1e4_cpt3','P_delta',1e4,'c_PT',3,'c_g',1), ...
    struct('name','Pdelta1e4_cg2_cpt3','P_delta',1e4,'c_PT',3,'c_g',2), ...
    struct('name','Pdelta1e4_cpt2p5','P_delta',1e4,'c_PT',2.5,'c_g',1), ...
    struct('name','Pdelta1e4_cg1p5_cpt3','P_delta',1e4,'c_PT',3,'c_g',1.5), ...
    struct('name','Pdelta1e4_t995_tau0p5','P_delta',1e4,'c_PT',3,'c_g',1, ...
        't_end',0.995,'transform_step',0.5), ...
    struct('name','Pdelta1e4_t995_tau0p25','P_delta',1e4,'c_PT',3,'c_g',1, ...
        't_end',0.995,'transform_step',0.25)};

pool=gcp('nocreate');workers=min(workers,6);
if isempty(pool)||pool.NumWorkers~=workers
    if ~isempty(pool),delete(pool);end
    parpool('Processes',workers);
end
rows=cell(numel(cfg),1);dq=parallel.pool.DataQueue;afterEach(dq,@show_row);
parfor i=1:numel(cfg)
    c=cfg{i};t_end=field_default(c,'t_end',0.99);
    tau_step=field_default(c,'transform_step',0.25);
    opts=struct('dt',dt_data,'n_gen',n_test,'n_steps',100, ...
        't_end',t_end,'transform_switch',0.9,'transform_step',tau_step, ...
        'trajectory_seeds',seeds,'state_constraint',state_constraint, ...
        'P_delta',c.P_delta,'P_u',1,'c_PT',c.c_PT,'c_g',c.c_g, ...
        'record_path',false,'record_control_trace',false);
    clock=tic;o=uniconflow_paper_guided_sample(net,scur,opts);seconds=toc(clock);
    bad=zeros(n_test,1);maxh=-inf(n_test,1);rollout_bad=zeros(n_test,1);
    rollout_rmse=zeros(n_test,1);
    for q=1:n_test
        for k=1:101
            h=state_constraint(o.states(:,k,q),k-1);hm=max(h(:));
            maxh(q)=max(maxh(q),hm);bad(q)=bad(q)+(hm>1e-8);
        end
        [~,Sr]=uniconflow_paper_reconstruct_actions(o.states(:,:,q),o.spec);
        rollout_rmse(q)=sqrt(mean((Sr-o.states(:,:,q)).^2,'all'));
        for k=1:101
            h=state_constraint(Sr(:,k),k-1);
            rollout_bad(q)=rollout_bad(q)+(max(h(:))>1e-8);
        end
    end
    rows{i}=struct('name',string(c.name),'P_delta',c.P_delta, ...
        'c_PT',c.c_PT,'c_g',c.c_g,'trajectory_safety',mean(bad==0), ...
        't_end',t_end,'transform_step',tau_step, ...
        'point_safety',1-sum(bad)/(101*n_test),'mean_bad_nodes',mean(bad), ...
        'rollout_trajectory_safety',mean(rollout_bad==0), ...
        'rollout_point_safety',1-sum(rollout_bad)/(101*n_test), ...
        'rollout_mean_bad_nodes',mean(rollout_bad), ...
        'rollout_rmse',mean(rollout_rmse), ...
        'median_hmax',median(maxh),'p95_hmax',prctile(maxh,95), ...
        'median_g',median(o.g_final),'p95_g',prctile(o.g_final,95), ...
        'seconds',seconds);
    send(dq,[i,100*rows{i}.trajectory_safety,100*rows{i}.point_safety, ...
        rows{i}.mean_bad_nodes,rows{i}.median_hmax,rows{i}.median_g,seconds]);
end
report=struct2table(vertcat(rows{:}));
report=sortrows(report,{'rollout_trajectory_safety','rollout_point_safety', ...
    'trajectory_safety','median_g'},{'descend','descend','descend','ascend'});
out=fullfile(root,'outputs','赛道UniConFlow_Stage1_ParamSweep');
if ~exist(out,'dir'),mkdir(out);end
writetable(report,fullfile(out,sprintf('Stage1_Sweep_%dSeeds.csv',n_test)));
save(fullfile(out,sprintf('Stage1_Sweep_%dSeeds.mat',n_test)), ...
    'report','cfg','seeds','-v7.3');
disp(report);
end
function show_row(x)
fprintf('cfg%d trajectory %.1f%% point %.2f%% bad %.2f hmed %.3g gmed %.3g %.1fs\n', ...
    x(1),x(2),x(3),x(4),x(5),x(6),x(7));
end
function v=field_default(s,f,d)
if isfield(s,f),v=s.(f);else,v=d;end
end
